version: '3'
services:
  minhbn-docker-webhook-auto-deploy:
    container_name: docker-webhook
    build: .
    #image: namminh2005/minh_ddw:latest
    #ports:
    #  - "8000:8080"
    environment:
      - PORT=8080
      - CONFIG=production
      - TOKEN=f0Hm3zA3Li7IbEyNe8KUddMHtdCLv71f
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # set this for use 'docker' CLI of host in container
      - ./volumes/conf:/usr/src/app/conf