version: '3'
services:
  minhbn-docker-webhook-auto-deploy:
    container_name: minhbn-docker-webhook-auto-deploy
    build: .
    #image: namminh2005/minh_ddw:latest
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
      - CONFIG=production
      - TOKEN=f0Hm3zA3Li7IbEyNe8KUddMHtdCLv71f
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock